openapi: 3.0.3
info:
  title: API Gestion des Équipes
  description: API permettant la gestion des équipes et leurs associations avec des groupements et personnes
  version: 1.0.0
  contact:
    name: PMU Matrix Compétence Team
servers:
  - url: 'http://localhost:8080'
    description: Serveur de développement

paths:
  /equipes:
    get:
      summary: Récupérer toutes les équipes
      operationId: getAllEquipes
      tags:
        - Equipes
      responses:
        '200':
          description: Liste des équipes récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Equipe'

    post:
      summary: Créer une nouvelle équipe
      operationId: createEquipe
      tags:
        - Equipes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEquipeRequest'
      responses:
        '201':
          description: Équipe créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Equipe'

  /equipes/{code}:
    parameters:
      - name: code
        in: path
        required: true
        schema:
          type: string
        description: Code unique de l'équipe

    get:
      summary: Récupérer une équipe par son code
      operationId: getEquipeByCode
      tags:
        - Equipes
      responses:
        '200':
          description: Équipe récupérée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Equipe'

    put:
      summary: Mettre à jour une équipe
      operationId: updateEquipe
      tags:
        - Equipes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEquipeRequest'
      responses:
        '200':
          description: Équipe mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Equipe'

    delete:
      summary: Supprimer une équipe
      operationId: deleteEquipe
      tags:
        - Equipes
      responses:
        '204':
          description: Équipe supprimée avec succès

  /equipes/{code}/profil-recherche:
    parameters:
      - name: code
        in: path
        required: true
        schema:
          type: string
        description: Code unique de l'équipe
        
    get:
      summary: Récupérer le profil de recherche d'une équipe
      operationId: getProfilRecherche
      tags:
        - Equipes
      responses:
        '200':
          description: Profil de recherche récupéré avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompetenceRequise'
        '404':
          description: Équipe non trouvée
          
    put:
      summary: Mettre à jour le profil de recherche d'une équipe
      operationId: updateProfilRecherche
      tags:
        - Equipes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CompetenceRequiseDto'
      responses:
        '200':
          description: Profil de recherche mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Equipe'
        '404':
          description: Équipe ou compétence non trouvée
          
    post:
      summary: Ajouter une compétence au profil de recherche
      operationId: addCompetenceRequiseToProfilRecherche
      tags:
        - Equipes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompetenceRequiseDto'
      responses:
        '201':
          description: Compétence ajoutée au profil avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Equipe'
        '404':
          description: Équipe ou compétence non trouvée
        '409':
          description: La compétence est déjà dans le profil
          
  /equipes/{code}/profil-recherche/{competenceLibelle}:
    parameters:
      - name: code
        in: path
        required: true
        schema:
          type: string
        description: Code unique de l'équipe
      - name: competenceLibelle
        in: path
        required: true
        schema:
          type: string
        description: Libellé de la compétence
        
    delete:
      summary: Supprimer une compétence du profil de recherche
      operationId: removeCompetenceRequiseFromProfilRecherche
      tags:
        - Equipes
      responses:
        '200':
          description: Compétence supprimée du profil avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Equipe'
        '404':
          description: Équipe ou compétence non trouvée
        
components:
  schemas:
    Equipe:
      type: object
      properties:
        code:
          type: string
          description: Code unique de l'équipe
          example: "EQ001"
        nom:
          type: string
          description: Nom de l'équipe
          example: "Équipe Backend"
        description:
          type: string
          description: Description de l'équipe
          example: "Équipe responsable du développement backend"
        groupement:
          $ref: '#/components/schemas/Groupement'
        membres:
          type: array
          items:
            $ref: '#/components/schemas/Personne'
          description: Liste des membres de l'équipe
        profilRecherche:
          type: array
          items:
            $ref: '#/components/schemas/CompetenceRequise'
          description: Profil de recherche de l'équipe (compétences souhaitées)
      required:
        - code
        - nom

    CreateEquipeRequest:
      type: object
      properties:
        code:
          type: string
          description: Code unique de l'équipe
          example: "EQ001"
        nom:
          type: string
          description: Nom de l'équipe
          example: "Équipe Backend"
        description:
          type: string
          description: Description de l'équipe
          example: "Équipe responsable du développement backend"
        groupementCode:
          type: string
          description: Code du groupement auquel l'équipe appartient
          example: "G001"
        profilRecherche:
          type: array
          items:
            $ref: '#/components/schemas/CompetenceRequiseDto'
          description: Profil de recherche de l'équipe
      required:
        - code
        - nom
        - groupementCode

    UpdateEquipeRequest:
      type: object
      properties:
        nom:
          type: string
          description: Nom de l'équipe
          example: "Équipe Backend V2"
        description:
          type: string
          description: Description de l'équipe
          example: "Équipe responsable du développement backend - Mise à jour"
        groupementCode:
          type: string
          description: Code du groupement auquel l'équipe appartient
          example: "G002"
        profilRecherche:
          type: array
          items:
            $ref: '#/components/schemas/CompetenceRequiseDto'
          description: Profil de recherche de l'équipe à mettre à jour

    Groupement:
      type: object
      properties:
        code:
          type: string
          description: Code unique du groupement
          example: "G001"
        libelle:
          type: string
          description: Libellé du groupement
          example: "Groupement IT"
        direction:
          type: string
          description: Direction à laquelle appartient le groupement
          example: "Direction Informatique"
      required:
        - code

    Personne:
      type: object
      properties:
        identifiant:
          type: string
          description: Identifiant unique de la personne
          example: "P12345"
        nom:
          type: string
          description: Nom de la personne
          example: "Dupont"
        prenom:
          type: string
          description: Prénom de la personne
          example: "Jean"
        poste:
          type: string
          description: Poste occupé par la personne
          example: "Développeur Senior"
        equipe:
          $ref: '#/components/schemas/Equipe'
      required:
        - identifiant
        - nom
        - prenom
        
    CompetenceRequise:
      type: object
      properties:
        competence:
          $ref: '#/components/schemas/Competence'
        noteRequise:
          $ref: '#/components/schemas/Note'
      required:
        - competence
        - noteRequise
        
    CompetenceRequiseDto:
      type: object
      properties:
        competenceLibelle:
          type: string
          description: Libellé de la compétence
          example: "JAVA"
        noteValeur:
          type: integer
          description: Valeur de la note requise
          example: 4
      required:
        - competenceLibelle
        - noteValeur
        
    Competence:
      type: object
      properties:
        libelle:
          type: string
          description: Libellé unique de la compétence
          example: "JAVA"
        description:
          type: string
          description: Description de la compétence
          example: "Programmation Java"
      required:
        - libelle
        
    Note:
      type: object
      properties:
        valeur:
          type: integer
          description: Valeur numérique de la note
          example: 4
        libelle:
          type: string
          description: Libellé de la note
          example: "Avancé"
      required:
        - valeur
        - libelle